/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidades.Acessos;
import Entidades.Atendimento;
import Entidades.AtendimentoPK;
import Entidades.Paciente;
import Entidades.Usuario;
import Repositorios.AcessosRepositorio;
import Repositorios.AtendimentoRepositorio;
import Repositorios.PacienteRepositorio;
import Repositorios.UsuarioRepositorio;
import com.github.lgooddatepicker.components.CalendarPanel;
import java.awt.Rectangle;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import static net.sf.dynamicreports.report.builder.DynamicReports.*;
import java.awt.Color;
import java.math.BigDecimal;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalTextAlignment;
import net.sf.dynamicreports.report.datasource.DRDataSource;
import net.sf.dynamicreports.report.exception.DRException;
import net.sf.jasperreports.engine.JRDataSource;

/**
 *
 * @author Alan
 */
public class AdminTela extends javax.swing.JFrame {

    public static String user;

    /**
     * Creates new form AdminTela
     */
    public AdminTela(String usuario) {
        user = usuario;
        initComponents();
        TabelaUsuario();
        TabelaPaciente();
        ListaMedico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpUsuario = new javax.swing.JPanel();
        btnInsUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        txtCpfUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAltUsuario = new javax.swing.JToggleButton();
        lblCpfUsuario = new javax.swing.JLabel();
        btnExcUsuario = new javax.swing.JToggleButton();
        jpPaciente = new javax.swing.JPanel();
        btnInsPaciente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPacientes = new javax.swing.JTable();
        txtCpfPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAltPaciente = new javax.swing.JToggleButton();
        lblCpfPaciente = new javax.swing.JLabel();
        jpAgendamento = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jltMedico = new javax.swing.JList<>();
        calendarData = new com.github.lgooddatepicker.components.CalendarPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jltHora = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbAtendimento = new javax.swing.JTable();
        btnAgendar = new javax.swing.JButton();
        btnAltAgenda = new javax.swing.JToggleButton();
        txtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbData = new javax.swing.JRadioButton();
        jbPaciente = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnExcAtendimento = new javax.swing.JToggleButton();
        jpRelatorio = new javax.swing.JPanel();
        btnReportAcessos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        calendarAcesso = new com.github.lgooddatepicker.components.CalendarPanel();
        calendarDiario = new com.github.lgooddatepicker.components.CalendarPanel();
        btnReportDiario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(640, 480));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jpUsuario.setPreferredSize(new java.awt.Dimension(640, 480));

        btnInsUsuario.setLabel("Inserir");
        btnInsUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsUsuarioMouseClicked(evt);
            }
        });

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Usuario", "Senha", "N.P.", "CPF", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuarios);

        txtCpfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfUsuarioKeyReleased(evt);
            }
        });

        jLabel1.setText("Digite o CPF do Usuário desejado:");

        btnAltUsuario.setText("Habilitar Alterações");
        btnAltUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltUsuarioMouseClicked(evt);
            }
        });

        lblCpfUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnExcUsuario.setText("Excluir");
        btnExcUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpUsuarioLayout.createSequentialGroup()
                                .addComponent(btnInsUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAltUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcUsuario)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsUsuario)
                    .addComponent(btnAltUsuario)
                    .addComponent(btnExcUsuario))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuários", jpUsuario);

        btnInsPaciente.setLabel("Inserir");
        btnInsPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsPacienteMouseClicked(evt);
            }
        });

        tbPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "SUS", "Data Nasc.", "Endereço", "Fone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPacientes);

        txtCpfPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfPacienteKeyReleased(evt);
            }
        });

        jLabel2.setText("Digite o CPF do Paciente desejado:");

        btnAltPaciente.setText("Habilitar Alterações");
        btnAltPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltPacienteMouseClicked(evt);
            }
        });

        lblCpfPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpPacienteLayout = new javax.swing.GroupLayout(jpPaciente);
        jpPaciente.setLayout(jpPacienteLayout);
        jpPacienteLayout.setHorizontalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPacienteLayout.createSequentialGroup()
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPacienteLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPacienteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpPacienteLayout.createSequentialGroup()
                                .addComponent(btnInsPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAltPaciente)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpPacienteLayout.setVerticalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsPaciente)
                    .addComponent(btnAltPaciente))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Pacientes", jpPaciente);

        jltMedico.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jltMedico.setPreferredSize(new java.awt.Dimension(250, 0));
        jltMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jltMedicoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jltMedico);

        calendarData.setSelectedDate(LocalDate.now());
        calendarData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarDataPropertyChange(evt);
            }
        });

        jltHora.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jltHora.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jltHora.setSelectedIndex(0);
        jScrollPane4.setViewportView(jltHora);

        tbAtendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Hora", "Paciente"
            }
        ));
        tbAtendimento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbAtendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAtendimentoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbAtendimento);

        btnAgendar.setText("Agendar");
        btnAgendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendarMouseClicked(evt);
            }
        });

        btnAltAgenda.setText("Habilitar Alterações");
        btnAltAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltAgendaMouseClicked(evt);
            }
        });

        txtData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataKeyReleased(evt);
            }
        });

        jLabel3.setText("Buscar por:");

        jLabel4.setText("Médicos:");

        buttonGroup1.add(jbData);
        jbData.setSelected(true);
        jbData.setText("Data");
        jbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDataMouseClicked(evt);
            }
        });

        buttonGroup1.add(jbPaciente);
        jbPaciente.setText("Paciente");
        jbPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPacienteMouseClicked(evt);
            }
        });

        jLabel5.setText("Digite o dado desejado:");

        btnExcAtendimento.setText("Excluir");
        btnExcAtendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcAtendimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpAgendamentoLayout = new javax.swing.GroupLayout(jpAgendamento);
        jpAgendamento.setLayout(jpAgendamentoLayout);
        jpAgendamentoLayout.setHorizontalGroup(
            jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgendamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jpAgendamentoLayout.createSequentialGroup()
                        .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpAgendamentoLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(calendarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgendar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jpAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbPaciente)
                            .addComponent(jbData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAltAgenda)
                        .addGap(22, 22, 22)
                        .addComponent(btnExcAtendimento)))
                .addContainerGap())
        );
        jpAgendamentoLayout.setVerticalGroup(
            jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgendamentoLayout.createSequentialGroup()
                .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgendamentoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(calendarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpAgendamentoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAgendamentoLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgendar))
                            .addGroup(jpAgendamentoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAltAgenda)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(btnExcAtendimento))
                    .addGroup(jpAgendamentoLayout.createSequentialGroup()
                        .addComponent(jbData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPaciente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agendamentos", jpAgendamento);

        btnReportAcessos.setText("Gerar Relatório");
        btnReportAcessos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportAcessosMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        calendarAcesso.setSelectedDate(LocalDate.now());

        calendarDiario.setSelectedDate(LocalDate.now());

        btnReportDiario.setText("Gerar Relatório");
        btnReportDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportDiarioMouseClicked(evt);
            }
        });

        jLabel6.setText("Relatório de Acessos:");

        jLabel7.setText("Relatório de Atendimentos Diários:");

        javax.swing.GroupLayout jpRelatorioLayout = new javax.swing.GroupLayout(jpRelatorio);
        jpRelatorio.setLayout(jpRelatorioLayout);
        jpRelatorioLayout.setHorizontalGroup(
            jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRelatorioLayout.createSequentialGroup()
                .addGroup(jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(calendarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnReportAcessos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(calendarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnReportDiario)))
                .addGap(51, 51, 51))
        );
        jpRelatorioLayout.setVerticalGroup(
            jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRelatorioLayout.createSequentialGroup()
                .addGroup(jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(1, 1, 1))
                    .addGroup(jpRelatorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calendarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnReportAcessos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calendarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnReportDiario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );

        jTabbedPane1.addTab("Relatórios", jpRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static boolean alterarUsuario = false, alterarPaciente = false, alterarAtendimento = false;
    private static boolean excluirUsuario = false, excluirAtendimento = false;
    private void btnAltUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltUsuarioMouseClicked
        // TODO add your handling code here:
        if (btnAltUsuario.isSelected() == true) {
            JOptionPane.showMessageDialog(null, "Clique no campo que deseja alterar.");
            btnAltUsuario.setText("Desabilitar Alterações");
            alterarUsuario = true;
        } else {
            btnAltUsuario.setText("Habilitar Alterações");
            alterarUsuario = false;
        }
    }//GEN-LAST:event_btnAltUsuarioMouseClicked

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // TODO add your handling code here:
        if (alterarUsuario == true) {
            AlterarUsuario();
        } else if (excluirUsuario == true) {
            ExcluirUsuario();
        }
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void btnInsUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsUsuarioMouseClicked
        // TODO add your handling code here:
        UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        Usuario usuario = new Usuario();
        String nome = JOptionPane.showInputDialog("Insira o Nome:");
        if (nome == null || nome.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        usuario.setNome(nome);
        String usuarioUser = null;
        Boolean userV = false;
        while (userV == false) {
            usuarioUser = JOptionPane.showInputDialog("Insira o Usuário:");
            if (usuarioUser == null || usuarioUser.isEmpty()) {
                cancelar();
                Thread.currentThread().stop();
            }
            if (!Character.isLetter(usuarioUser.charAt(0))) {
                JOptionPane.showMessageDialog(null, "O usuario deve ser iniciado com uma letra.");
            } else {
                userV = true;
            }
        }
        usuario.setUsuario(usuarioUser);
        String senha = JOptionPane.showInputDialog("Insira a Senha:");
        if (senha == null || senha.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        usuario.setSenha(senha);
        String np = JOptionPane.showInputDialog("Insira o Nível de Privilégio: (1) Médico, (2) Oficial, (3) Administrador.");
        if (np == null || np.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        while ("1" != np.intern() && "2" != np.intern() && "3" != np.intern()) {
            np = JOptionPane.showInputDialog("Opção Inválida. Digite uma das opções: (1) Médico, (2) Oficial, (3) Administrador.");
            if (np == null) {
                cancelar();
                Thread.currentThread().stop();
            }
        }
        usuario.setNP(Integer.parseInt(np));
        String cpf = null;
        Boolean cpfV = false;
        while (cpfV == false) {
            cpf = JOptionPane.showInputDialog("Insira o CPF:");
            if (cpf == null || cpf.isEmpty()) {
                cancelar();
                Thread.currentThread().stop();
            } else if (AdminTela.isValidCPF(cpf) == false) {
                JOptionPane.showMessageDialog(null, "Digite um CPF válido.");
            } else {
                cpfV = true;
            }
        }
        usuario.setCPF(cpf);
        String rg = JOptionPane.showInputDialog("Insira o RG:");
        if (rg == null || rg.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        usuario.setRG(rg);
        usuarioRepositorio.inserir(usuario);
        TabelaUsuario();
        ListaMedico();
    }//GEN-LAST:event_btnInsUsuarioMouseClicked

    private void txtCpfUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfUsuarioKeyReleased
        // TODO add your handling code here:
        Integer rows = tbUsuarios.getRowCount();
        for (int i = 0; i < rows; i++) {
            if (tbUsuarios.getValueAt(i, 4).equals(txtCpfUsuario.getText())) {
                tbUsuarios.setRowSelectionInterval(i, i);
                tbUsuarios.scrollRectToVisible(new Rectangle(tbUsuarios.getCellRect(i, 0, true)));
                lblCpfUsuario.setText("Usuário encontrado.");
                Thread.currentThread().stop();
            } else {
                lblCpfUsuario.setText("Nenhum Usuário com este CPF foi encontrado.");
            }
            if (txtCpfUsuario.getText().equals("")) {
                lblCpfUsuario.setText(null);
            }
        }
    }//GEN-LAST:event_txtCpfUsuarioKeyReleased

    private void btnExcUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcUsuarioMouseClicked
        // TODO add your handling code here:
        if (btnExcUsuario.isSelected() == true) {
            JOptionPane.showMessageDialog(null, "Clique no partido que deseja excluir.");
            btnExcUsuario.setText("Cancelar Exclusão");
            excluirUsuario = true;
        } else {
            btnExcUsuario.setText("Excluir");
            excluirUsuario = false;
        }
    }//GEN-LAST:event_btnExcUsuarioMouseClicked

    private void btnInsPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsPacienteMouseClicked
        // TODO add your handling code here:
        PacienteRepositorio pacienteRepositorio = new PacienteRepositorio();
        Paciente paciente = new Paciente();
        String nome = JOptionPane.showInputDialog("Insira o Nome:");
        if (nome == null || nome.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        paciente.setNome(nome);
        String cpf = null;
        Boolean cpfV = false;
        while (cpfV == false) {
            cpf = JOptionPane.showInputDialog("Insira o CPF:");
            if (cpf == null || cpf.isEmpty()) {
                cancelar();
                Thread.currentThread().stop();
            } else if (AdminTela.isValidCPF(cpf) == false) {
                JOptionPane.showMessageDialog(null, "Digite um CPF válido.");
            } else {
                cpfV = true;
            }
        }
        paciente.setCPF(cpf);
        String sus = JOptionPane.showInputDialog("Insira o código SUS:");
        if (sus == null || sus.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        paciente.setSUS(sus);

        Boolean dataV = false;
        String data = null;
        while (dataV == false) {

            data = JOptionPane.showInputDialog("Insira a data de nascimento:");
            System.out.println("teste: " + data);
            DateFormat dtf = new SimpleDateFormat("dd/MM/yyyy");
            dtf.setLenient(false);
            Date dt = null;
            try {
                dt = dtf.parse(data);
                dataV = true;
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Insira uma data válida.");
            } catch (NullPointerException e) {
                cancelar();
                Thread.currentThread().stop();
            }

        }
        paciente.setDataNasc(data);
        String end = JOptionPane.showInputDialog("Insira o Endereço:");
        if (end == null || end.isEmpty()) {
            cancelar();
            Thread.currentThread().stop();
        }
        paciente.setEndereco(end);
        String fone = null;
        Boolean foneV = false;
        while (foneV == false) {
            fone = JOptionPane.showInputDialog("Insira o Telefone:");
            if (fone == null || fone.isEmpty()) {
                cancelar();
                Thread.currentThread().stop();
            }
            for (int i = 0; i < fone.length(); i++) {
                if (Character.isLetter(fone.charAt(i))) {
                    JOptionPane.showMessageDialog(null, "Digite um telefone válido.");
                } else if (i == fone.length() - 1) {
                    foneV = true;
                }
            }
        }
        paciente.setFone(fone);
        pacienteRepositorio.inserir(paciente);
        TabelaPaciente();
    }//GEN-LAST:event_btnInsPacienteMouseClicked

    private void tbPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPacientesMouseClicked
        // TODO add your handling code here:
        if (alterarPaciente == true) {
            AlterarPaciente();
        }
    }//GEN-LAST:event_tbPacientesMouseClicked

    private void txtCpfPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfPacienteKeyReleased
        // TODO add your handling code here:
        Integer rows = tbPacientes.getRowCount();
        for (int i = 0; i < rows; i++) {
            if (tbPacientes.getValueAt(i, 1).equals(txtCpfPaciente.getText())) {
                tbPacientes.setRowSelectionInterval(i, i);
                tbPacientes.scrollRectToVisible(new Rectangle(tbPacientes.getCellRect(i, 0, true)));
                lblCpfPaciente.setText("Paciente encontrado.");
                Thread.currentThread().stop();
            } else {
                lblCpfPaciente.setText("Nenhum Paciente com este CPF foi encontrado.");
            }
            if (txtCpfPaciente.getText().equals("")) {
                lblCpfPaciente.setText(null);
            }
        }
    }//GEN-LAST:event_txtCpfPacienteKeyReleased

    private void btnAltPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltPacienteMouseClicked
        // TODO add your handling code here:
        if (btnAltPaciente.isSelected() == true) {
            JOptionPane.showMessageDialog(null, "Clique no campo que deseja alterar.");
            btnAltPaciente.setText("Desabilitar Alterações");
            alterarPaciente = true;
        } else {
            btnAltPaciente.setText("Habilitar Alterações");
            alterarPaciente = false;
        }
    }//GEN-LAST:event_btnAltPacienteMouseClicked

    private void jltMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jltMedicoMouseClicked
        // TODO add your handling code here:
        TabelaAtendimento(jltMedico.getSelectedValue());
    }//GEN-LAST:event_jltMedicoMouseClicked

    private void btnAgendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarMouseClicked
        // TODO add your handling code here:
        Atendimento atendimento = new Atendimento();
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoRepositorio();
        AtendimentoPK atendimentoPK = new AtendimentoPK();
        PacienteRepositorio pacienteRepositorio = new PacienteRepositorio();

        if (jltHora.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Primeiramente selecione um horário.");
            Thread.currentThread().stop();
        }

        LocalDate selDate = calendarData.getSelectedDate();

        if (selDate.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "Selecione uma data superior ou igual a data atual.");
            cancelar();
            Thread.currentThread().stop();
        }

        String formatted = selDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

        atendimentoPK.setData(formatted);
        String hora = jltHora.getSelectedValue();
        if (hora.charAt(0) == '<') {
            JOptionPane.showMessageDialog(null, "Já existe uma consulta agendada neste horário!");
            Thread.currentThread().stop();
        }
        atendimentoPK.setHora(hora);
        atendimentoPK.setMedico(jltMedico.getSelectedValue());
        atendimento.setId(atendimentoPK);
        String cpf = JOptionPane.showInputDialog(null, "Digite o CPF do Paciente desejado:");
        if (cpf == null || cpf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum paciente com este CPF foi encontrado.");
            Thread.currentThread().stop();
        }
        Paciente paciente = pacienteRepositorio.buscarPorCpf(cpf);
        if (paciente == null) {
            JOptionPane.showMessageDialog(null, "Nenhum Paciente com este CPF foi encontrado.");
            Thread.currentThread().stop();
        }
        atendimento.setPaciente(paciente);
        atendimentoRepositorio.inserir(atendimento);
        TabelaAtendimento(jltMedico.getSelectedValue());
    }//GEN-LAST:event_btnAgendarMouseClicked

    private void btnAltAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltAgendaMouseClicked
        // TODO add your handling code here:
        if (btnAltAgenda.isSelected() == true) {
            JOptionPane.showMessageDialog(null, "Clique no campo que deseja alterar.");
            btnAltAgenda.setText("Desabilitar Alterações");
            alterarAtendimento = true;
        } else {
            btnAltAgenda.setText("Habilitar Alterações");
            alterarAtendimento = false;
        }


    }//GEN-LAST:event_btnAltAgendaMouseClicked

    private void calendarDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarDataPropertyChange
        // TODO add your handling code here:
        if (jpAgendamento.isShowing()) {
            if (jltMedico.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(null, "Primeiramente selecione um médico.");
                Thread.currentThread().stop();
            } else {
                horarios();
            }
        }
    }//GEN-LAST:event_calendarDataPropertyChange

    private void txtDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataKeyReleased
        // TODO add your handling code here:
        String medico = jltMedico.getSelectedValue();
        if (jbData.isSelected()) {
            if (txtData.getText().length() == 10 && tbAtendimento.getRowCount() != 0) {
                TabelaAtendimento(medico);
            }
        } else if (jbPaciente.isSelected() && tbAtendimento.getRowCount() != 0) {
            TabelaAtendimento(medico);
        }
        if (txtData.getText().isEmpty() && tbAtendimento.getRowCount() != 0) {
            TabelaAtendimento(medico);
        }

        Integer rows = tbAtendimento.getRowCount();
        Integer col = null;
        for (int i = 0; i < rows; i++) {
            if (jbData.isSelected()) {
                col = 0;
            } else if (jbPaciente.isSelected()) {
                col = 2;
            }
            if (tbAtendimento.getValueAt(i, col).equals(txtData.getText())) {
                tbAtendimento.setRowSelectionInterval(i, i);
                tbAtendimento.scrollRectToVisible(new Rectangle(tbAtendimento.getCellRect(i, 0, true)));
                Thread.currentThread().stop();
            } else {
            }

        }
    }//GEN-LAST:event_txtDataKeyReleased

    private void jbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDataMouseClicked
        // TODO add your handling code here:
        txtData.setText(null);
    }//GEN-LAST:event_jbDataMouseClicked

    private void jbPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPacienteMouseClicked
        // TODO add your handling code here:
        txtData.setText(null);
    }//GEN-LAST:event_jbPacienteMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if (!jpPaciente.isShowing() && alterarPaciente == true) {
            alterarPaciente = false;
            btnAltPaciente.setSelected(false);
            btnAltPaciente.setText("Habilitar Alterações");
        }

        if (!jpUsuario.isShowing() && alterarUsuario == true) {
            alterarUsuario = false;
            btnAltUsuario.setSelected(false);
            btnAltUsuario.setText("Habilitar Alterações");
        }

        if (!jpAgendamento.isShowing() && alterarAtendimento == true) {
            alterarAtendimento = false;
            btnAltAgenda.setSelected(false);
            btnAltAgenda.setText("Habilitar Alterações");
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void tbAtendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAtendimentoMouseClicked
        // TODO add your handling code here:
        if (alterarAtendimento == true) {
            AlterarAtendimento();
        } else if (excluirAtendimento == true) {
            ExcluirAtendimento();
        }
    }//GEN-LAST:event_tbAtendimentoMouseClicked

    private void btnExcAtendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcAtendimentoMouseClicked
        // TODO add your handling code here:
        if (btnExcAtendimento.isSelected() == true) {
            JOptionPane.showMessageDialog(null, "Clique no partido que deseja excluir.");
            btnExcAtendimento.setText("Cancelar Exclusão");
            excluirAtendimento = true;
        } else {
            btnExcAtendimento.setText("Excluir");
            excluirAtendimento = false;
        }
    }//GEN-LAST:event_btnExcAtendimentoMouseClicked

    private void btnReportAcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportAcessosMouseClicked
        // TODO add your handling code here:
        StyleBuilder boldStyle = stl.style().bold();
        StyleBuilder boldCenteredStyle = stl.style(boldStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER);
        StyleBuilder columnTitleStyle = stl.style(boldCenteredStyle)
                .setBorder(stl.pen1Point())
                .setBackgroundColor(Color.LIGHT_GRAY);
        try {
            try {
                report()//create new report design
                        .setColumnTitleStyle(columnTitleStyle)
                        .highlightDetailEvenRows()
                        .columns(//add columns
                                //            title,     field name     data type
                                col.column("Usuário", "usuario", type.stringType()),
                                col.column("Nome", "nome", type.stringType()),
                                col.column("Horário", "horario", type.stringType()))
                        .title(cmp.text("Relatório de Acessos de "
                                + calendarAcesso.getSelectedDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).setStyle(boldCenteredStyle))//shows report title
                        .pageFooter(cmp.pageXofY().setStyle(boldCenteredStyle))//shows number of page at page footer
                        .setDataSource(createDataSourceAcessos())//set datasource
                        .show(false)
                        ;//create and show report
            } catch (ParseException ex) {
                Logger.getLogger(AdminTela.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportAcessosMouseClicked

    private void btnReportDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportDiarioMouseClicked
        // TODO add your handling code here:
        StyleBuilder boldStyle = stl.style().bold();
        StyleBuilder boldCenteredStyle = stl.style(boldStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER);
        StyleBuilder columnTitleStyle = stl.style(boldCenteredStyle)
                .setBorder(stl.pen1Point())
                .setBackgroundColor(Color.LIGHT_GRAY);
        try {
            report()//create new report design
                    .setColumnTitleStyle(columnTitleStyle)
                    .highlightDetailEvenRows()
                    .columns(//add columns
                            //            title,     field name     data type
                            col.column("Horário", "horario", type.stringType()),
                            col.column("Médico", "medico", type.stringType()),
                            col.column("Paciente", "paciente", type.stringType()),
                            col.column("CPF do Paciente", "cpf", type.stringType()))
                    .title(cmp.text("Relatório de Atendimentos Diários de "
                            + calendarAcesso.getSelectedDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).setStyle(boldCenteredStyle))//shows report title
                    .pageFooter(cmp.pageXofY().setStyle(boldCenteredStyle))//shows number of page at page footer
                    .setDataSource(createDataSourceDiario())//set datasource
                    .show();//create and show report
        } catch (DRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportDiarioMouseClicked

    private JRDataSource createDataSourceAcessos() throws ParseException {
        AcessosRepositorio acessosRepositorio = new AcessosRepositorio();
        LocalDate selDate = calendarAcesso.getSelectedDate();
        String formatted = selDate.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        List<Acessos> acessos = acessosRepositorio.buscarPorData(formatted);
        DRDataSource dataSource = new DRDataSource("usuario", "nome", "horario");
        if (!acessos.isEmpty() || acessos != null) {
            for (Acessos acesso : acessos) {
                String min = Integer.toString(acesso.getData().getMinutes());
                if(min.length() < 2){
                    min = "0"+min;
                }
                dataSource.add(acesso.getUsuario(), acesso.getNome(), acesso.getData().getHours() + ":" + min);
            }
        }
        return dataSource;
    }

    private JRDataSource createDataSourceDiario() {
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoRepositorio();
        LocalDate selDate = calendarAcesso.getSelectedDate();
        String formatted = selDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        List<Atendimento> atendimentos = atendimentoRepositorio.buscarPorData(formatted);
        DRDataSource dataSource = new DRDataSource("horario", "medico", "paciente", "cpf");
        if (!atendimentos.isEmpty() || atendimentos != null) {
            for (Atendimento atendimento : atendimentos) {
                AtendimentoPK atendimentoPK = atendimento.getId();
                dataSource.add(atendimentoPK.getHora(), atendimentoPK.getMedico(), atendimento.getPaciente().getNome(), atendimento.getPaciente().getCPF());
            }
        }
        return dataSource;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTela(user).setVisible(true);
            }
        });
    }

    public void cancelar() {
        JOptionPane.showMessageDialog(null, "Operação cancelada!");
    }

    public void AlterarUsuario() {
        UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        Integer row = tbUsuarios.getSelectedRow();
        Integer col = tbUsuarios.getSelectedColumn();
        String title = (String) tbUsuarios.getColumnName(col);
        String nome = (String) tbUsuarios.getValueAt(row, 0);
        Usuario usuario = usuarioRepositorio.buscarPorNome(nome);
        switch (title) {
            case "Nome":
                String usuarioName = null;
                usuarioName = JOptionPane.showInputDialog("Insira o Nome:");
                if (usuarioName == null || usuarioName.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                usuario.setNome(usuarioName);
                break;
            case "Usuario":
                String usuarioUser = null;
                Boolean userV = false;
                while (userV == false) {
                    usuarioUser = JOptionPane.showInputDialog("Insira o Usuário:");
                    if (usuarioUser == null || usuarioUser.isEmpty()) {
                        cancelar();
                        Thread.currentThread().stop();
                    }
                    if (!Character.isLetter(usuarioUser.charAt(0))) {
                        JOptionPane.showMessageDialog(null, "O usuario deve ser iniciado com uma letra.");
                    } else {
                        userV = true;
                    }
                }
                usuario.setUsuario(usuarioUser);
                break;
            case "Senha":
                String senha = JOptionPane.showInputDialog("Insira a Senha:");
                if (senha == null || senha.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                usuario.setSenha(senha);
                break;
            case "NP":
                String np = JOptionPane.showInputDialog("Insira o Nível de Privilégio: (1) Médico, (2) Oficial, (3) Administrador.");
                if (np == null || np.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                while ("1" != np.intern() && "2" != np.intern() && "3" != np.intern()) {
                    np = JOptionPane.showInputDialog("Opção Inválida. Digite uma das opções: (1) Médico, (2) Oficial, (3) Administrador.");
                    if (np == null) {
                        cancelar();
                        Thread.currentThread().stop();
                    }
                }
                usuario.setNP(Integer.parseInt(np));
                break;
            case "CPF":
                String cpf = null;
                Boolean cpfV = false;
                while (cpfV == false) {
                    cpf = JOptionPane.showInputDialog("Insira o CPF:");
                    if (cpf == null || cpf.isEmpty()) {
                        cancelar();
                        Thread.currentThread().stop();
                    } else if (AdminTela.isValidCPF(cpf) == false) {
                        JOptionPane.showMessageDialog(null, "Digite um CPF válido.");
                    } else {
                        cpfV = true;
                    }
                }
                usuario.setCPF(cpf);
                break;
            case "RG":
                String rg = JOptionPane.showInputDialog("Insira o RG:");
                if (rg == null || rg.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                usuario.setRG(rg);
                break;
        }
        usuarioRepositorio.editar(usuario);
        TabelaUsuario();
        ListaMedico();
    }

    public void ExcluirUsuario() {
        UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        Integer row = tbUsuarios.getSelectedRow();
        String nome = (String) tbUsuarios.getValueAt(row, 0);
        Usuario usuario = usuarioRepositorio.buscarPorNome(nome);
        usuarioRepositorio.excluir(usuario);
        TabelaUsuario();
        ListaMedico();
        JOptionPane.showMessageDialog(null, "Excluido Com Sucesso.");
        btnExcUsuario.setText("Excluir");
        excluirUsuario = false;
        btnExcUsuario.setSelected(false);
    }

    public void TabelaUsuario() {
        UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        List<Usuario> usuarios = usuarioRepositorio.buscarTudoOrdenado();
        String[] colunasTabela = new String[]{"Nome", "Usuario", "Senha", "NP", "CPF", "RG"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        tbUsuarios.setModel(modeloTabela);
        for (Usuario usuario : usuarios) {
            String np = null;
            if (usuario.getNP() == 1) {
                np = "Médico";
            } else if (usuario.getNP() == 2) {
                np = "Secretário";
            } else if (usuario.getNP() == 3) {
                np = "Administrador";
            }
            modeloTabela.addRow(new Object[]{usuario.getNome(), usuario.getUsuario(), usuario.getSenha(),
                np, usuario.getCPF(), usuario.getRG()});
        }
    }

    public void AlterarPaciente() {
        PacienteRepositorio pacienteRepositorio = new PacienteRepositorio();
        Integer row = tbPacientes.getSelectedRow();
        Integer col = tbPacientes.getSelectedColumn();
        String title = (String) tbPacientes.getColumnName(col);
        String nome = (String) tbPacientes.getValueAt(row, 0);
        Paciente paciente = pacienteRepositorio.buscarPorNome(nome);
        switch (title) {
            case "Nome":
                String name = JOptionPane.showInputDialog("Insira o Nome:");
                if (name == null || name.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                paciente.setNome(name);
                break;
            case "CPF":
                String cpf = null;
                Boolean cpfV = false;
                while (cpfV == false) {
                    cpf = JOptionPane.showInputDialog("Insira o CPF:");
                    if (cpf == null || cpf.isEmpty()) {
                        cancelar();
                        Thread.currentThread().stop();
                    } else if (AdminTela.isValidCPF(cpf) == false) {
                        JOptionPane.showMessageDialog(null, "Digite um CPF válido.");
                    } else {
                        cpfV = true;
                    }
                }
                paciente.setCPF(cpf);
                break;
            case "SUS":
                String sus = JOptionPane.showInputDialog("Insira o código SUS:");
                if (sus == null || sus.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                paciente.setSUS(sus);
                break;
            case "Data Nasc.":
                Boolean dataV = false;
                String data = null;
                while (dataV == false) {

                    data = JOptionPane.showInputDialog("Insira a data de nascimento:");
                    System.out.println("teste: " + data);
                    DateFormat dtf = new SimpleDateFormat("dd/MM/yyyy");
                    dtf.setLenient(false);
                    Date dt = null;
                    try {
                        dt = dtf.parse(data);
                        dataV = true;
                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(null, "Insira uma data válida.");
                    } catch (NullPointerException e) {
                        cancelar();
                        Thread.currentThread().stop();
                    }

                }
                paciente.setDataNasc(data);
                break;
            case "Endereço":
                String end = JOptionPane.showInputDialog("Insira o Endereço:");
                if (end == null || end.isEmpty()) {
                    cancelar();
                    Thread.currentThread().stop();
                }
                paciente.setEndereco(end);
                break;
            case "Fone":
                String fone = null;
                Boolean foneV = false;
                while (foneV == false) {
                    fone = JOptionPane.showInputDialog("Insira o Telefone:");
                    if (fone == null || fone.isEmpty()) {
                        cancelar();
                        Thread.currentThread().stop();
                    }
                    for (int i = 0; i < fone.length(); i++) {
                        if (Character.isLetter(fone.charAt(i))) {
                            JOptionPane.showMessageDialog(null, "Digite um telefone válido.");
                        } else if (i == fone.length() - 1) {
                            foneV = true;
                        }
                    }
                }
                paciente.setFone(fone);
                break;
            default:
                break;
        }
        pacienteRepositorio.editar(paciente);
        TabelaPaciente();
    }

    public void TabelaPaciente() {
        PacienteRepositorio pacienteRepositorio = new PacienteRepositorio();
        List<Paciente> pacientes = pacienteRepositorio.buscarTudoOrdenado();
        String[] colunasTabela = new String[]{"Nome", "CPF", "SUS", "Data Nasc.", "Endereço", "Fone"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        tbPacientes.setModel(modeloTabela);
        for (Paciente paciente : pacientes) {
            modeloTabela.addRow(new Object[]{paciente.getNome(), paciente.getCPF(), paciente.getSUS(),
                paciente.getDataNasc(), paciente.getEndereco(), paciente.getFone()});

        }
    }

    public void ListaMedico() {
        UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        List<Usuario> usuarios = usuarioRepositorio.buscarPorNP(1);

        DefaultListModel model = new DefaultListModel();
        jltMedico.setModel(model);
        for (Usuario usuario : usuarios) {
            model.addElement(usuario.getNome());
        }
    }

    public void TabelaAtendimento(String medico) {
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoRepositorio();
        List<Atendimento> atendimentos = null;
        Date dt = null;
        if (!txtData.getText().isEmpty() && jbPaciente.isSelected()) {
            atendimentos = atendimentoRepositorio.buscarPorPacienteMedico(medico, txtData.getText());
            if (atendimentos == null || atendimentos.isEmpty()) {
                Thread.currentThread().stop();
            }
        } else if (!txtData.getText().isEmpty() && jbData.isSelected()) {
            try {
                dt = new SimpleDateFormat("dd/MM/yyyy").parse(txtData.getText());
            } catch (ParseException ex) {
                Logger.getLogger(AdminTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
            String formatted = fm.format(dt);
            atendimentos = atendimentoRepositorio.buscarPorDataMedico(medico, formatted);
        } else {
            atendimentos = atendimentoRepositorio.buscarPorMedico(medico);
        }

        String[] colunasTabela = new String[]{"Data", "Hora", "Paciente"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        tbAtendimento.setModel(modeloTabela);
        if (atendimentos == null && txtData.getText().isEmpty()) {
            horarios();
            Thread.currentThread().stop();
        } else {

            for (Atendimento atendimento : atendimentos) {
                LocalDate local = LocalDate.parse(atendimento.getId().getData());
                String data = local.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                modeloTabela.addRow(new Object[]{data, atendimento.getId().getHora(),
                    atendimento.getPaciente().getNome()});
            }
        }
        horarios();
    }

    public void horarios() {
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoRepositorio();
        LocalDate selDate = calendarData.getSelectedDate();
        String formatted = selDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        String medico = jltMedico.getSelectedValue();
        List<Atendimento> atendimentos = atendimentoRepositorio.buscarPorDataMedico(medico, formatted);
        DefaultListModel hModel = new DefaultListModel();
        String[] list = new String[]{"08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30 ", "12:00",
            "12:30", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"};
        int qtdHora = list.length;
        for (int i = 0; i < qtdHora; i++) {
            hModel.addElement(list[i]);
        }
        if (atendimentos == null) {
            jltHora.setModel(hModel);
            Thread.currentThread().stop();
        }
        for (Atendimento atendimento : atendimentos) {
            for (int i = 0; i < qtdHora; i++) {
                if (atendimento.getId().getHora().equals(hModel.getElementAt(i))) {
                    hModel.setElementAt("<html><p style='color:red'>" + hModel.getElementAt(i) + "</p></html>", i);

                }
            }
        }
        jltHora.setModel(hModel);
    }

    public void AlterarAtendimento() {
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoRepositorio();
        Integer row = tbAtendimento.getSelectedRow();
        Integer col = tbAtendimento.getSelectedColumn();
        String title = (String) tbAtendimento.getColumnName(col);
        String valor = (String) tbAtendimento.getValueAt(row, 0);
        Date dtBusca = null;
        try {
            dtBusca = new SimpleDateFormat("dd/MM/yyyy").parse(valor);
        } catch (ParseException ex) {
            Logger.getLogger(AdminTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String formatted = fm.format(dtBusca);
        Atendimento atendimento = atendimentoRepositorio.buscarUnicaDataMedico(jltMedico.getSelectedValue(), formatted);
        switch (title) {
            case "Data":
                JOptionPane.showMessageDialog(null, "Não é possível alterar a data de um atendimento diretamente."
                        + "\nExclua o atendimento atual e agende novamente na data desejada.");
                break;
            case "Hora":
                JOptionPane.showMessageDialog(null, "Não é possível alterar o horário de um atendimento diretamente."
                        + "\nExclua o atendimento atual e agende novamente no horário desejado.");
                break;
            case "Paciente":
                Paciente paciente = null;
                String cpf = null;
                Boolean cpfV = false;
                while (cpfV == false) {
                    cpf = JOptionPane.showInputDialog("Insira o CPF do Paciente:");
                    if (cpf == null || cpf.isEmpty()) {
                        cancelar();
                        Thread.currentThread().stop();
                    } else {
                        PacienteRepositorio pacienteRepositorio = new PacienteRepositorio();
                        paciente = pacienteRepositorio.buscarPorCpf(cpf);
                        if (paciente == null) {
                            JOptionPane.showMessageDialog(null, "Nenhum Paciente com este CPF foi encontrado.");
                        } else {
                            cpfV = true;
                        }
                    }
                }
                atendimento.setPaciente(paciente);
                break;
            default:
                break;
        }
        atendimentoRepositorio.editar(atendimento);
        TabelaAtendimento(jltMedico.getSelectedValue());
    }

    public void ExcluirAtendimento() {
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoRepositorio();
        Integer row = tbAtendimento.getSelectedRow();
        Integer col = tbAtendimento.getSelectedColumn();
        String title = (String) tbAtendimento.getColumnName(col);
        String valor = (String) tbAtendimento.getValueAt(row, 0);
        Date dtBusca = null;
        try {
            dtBusca = new SimpleDateFormat("dd/MM/yyyy").parse(valor);
        } catch (ParseException ex) {
            Logger.getLogger(AdminTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String formatted = fm.format(dtBusca);
        Atendimento atendimento = atendimentoRepositorio.buscarUnicaDataMedico(jltMedico.getSelectedValue(), formatted);
        atendimentoRepositorio.excluir(atendimento);
        JOptionPane.showMessageDialog(null, "Excluido Com Sucesso.");
        btnExcAtendimento.setText("Excluir");
        excluirAtendimento = false;
        btnExcAtendimento.setSelected(false);
        TabelaAtendimento(jltMedico.getSelectedValue());
    }

    /*@Override
    public void dispose() {
    new Login().setVisible(true);
    super.dispose();
    }*/
    private static final int[] pesoCPF = {11, 10, 9, 8, 7, 6, 5, 4, 3, 2};

    private static int calcularDigito(String str, int[] peso) {
        int soma = 0;
        for (int indice = str.length() - 1, digito; indice >= 0; indice--) {
            digito = Integer.parseInt(str.substring(indice, indice + 1));
            soma += digito * peso[peso.length - str.length() + indice];
        }
        soma = 11 - soma % 11;
        return soma > 9 ? 0 : soma;
    }

    public static boolean isValidCPF(String cpf) {
        if ((cpf == null) || (cpf.length() != 11)) {
            return false;
        }

        Integer digito1 = calcularDigito(cpf.substring(0, 9), pesoCPF);
        Integer digito2 = calcularDigito(cpf.substring(0, 9) + digito1, pesoCPF);
        return cpf.equals(cpf.substring(0, 9) + digito1.toString() + digito2.toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JToggleButton btnAltAgenda;
    private javax.swing.JToggleButton btnAltPaciente;
    private javax.swing.JToggleButton btnAltUsuario;
    private javax.swing.JToggleButton btnExcAtendimento;
    private javax.swing.JToggleButton btnExcUsuario;
    private javax.swing.JButton btnInsPaciente;
    private javax.swing.JButton btnInsUsuario;
    private javax.swing.JButton btnReportAcessos;
    private javax.swing.JButton btnReportDiario;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.github.lgooddatepicker.components.CalendarPanel calendarAcesso;
    private com.github.lgooddatepicker.components.CalendarPanel calendarData;
    private com.github.lgooddatepicker.components.CalendarPanel calendarDiario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jbData;
    private javax.swing.JRadioButton jbPaciente;
    private javax.swing.JList<String> jltHora;
    private javax.swing.JList<String> jltMedico;
    private javax.swing.JPanel jpAgendamento;
    private javax.swing.JPanel jpPaciente;
    private javax.swing.JPanel jpRelatorio;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblCpfUsuario;
    private javax.swing.JTable tbAtendimento;
    private javax.swing.JTable tbPacientes;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtCpfUsuario;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables
}
